### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by LappleApple** [zalando/environmental#6]
Hey, this seems potentially useful to non-Zalandos but still in development. Is that accurate? Do you think this project will justify a solid README and promotion? LMK!

**Comment by rafaelcaricio** [comment]
This project is definitely useful for non-Zalando Python community. It is already used by [Lizzy](https://github.com/zalando/lizzy/blob/master/requirements.txt#L2) and probably others. So I would say it is ready to be used by everyone.

It is a pretty simple and generic project, but useful.

**Comment by LappleApple** [comment]
Thanks, Rafael! I'll add it to my list ...
